import { ISO_3166_1_Record } from '../../src/types/record';

export const generateCode = (records: ISO_3166_1_Record[]): string => {
  const names = records.map(({ name }) => name);
  const namesFr = records.map(({ name_fr }) => name_fr);
  const alpha2Codes = records.map(({ alpha2 }) => alpha2);
  const alpha3Codes = records.map(({ alpha3 }) => alpha3);
  const numericCodes = records.map(({ numeric }) => numeric);

  const source = `
// DO NOT MODIFY THIS FILE DIRECTLY!
// This file is automatically generated by scripts/generate-code/generate-code.ts
/**
 * ISO 3166-1 country code records
 */
export const records = ${JSON.stringify(records)} as const;

/**
 * ISO 3166-1 country code English short names
 */
export const names = ${JSON.stringify(names)} as const;
/**
 * ISO 3166-1 country code English short names
 */
export type EnglishShortName = typeof names[number];

/**
 * ISO 3166-1 country code French short names
 */
export const namesFr = ${JSON.stringify(namesFr)} as const;
/**
 * ISO 3166-1 country code French short names
 */
export type FrenchShortName = typeof namesFr[number];

/**
 * ISO 3166-1 Alpha-2 codes
 */
export const alpha2Codes = ${JSON.stringify(alpha2Codes)} as const;
/**
 * ISO 3166-1 Alpha-2 codes
 */
export type Alpha2Code = typeof alpha2Codes[number];

/**
 * ISO 3166-1 Alpha-3 codes
 */
export const alpha3Codes = ${JSON.stringify(alpha3Codes)} as const;
/**
 * ISO 3166-1 Alpha-3 codes
 */
export type Alpha3Code = typeof alpha3Codes[number];

/**
 * ISO 3166-1 Numeric codes
 */
export const numericCodes = ${JSON.stringify(numericCodes)} as const;
/**
 * ISO 3166-1 Numeric codes
 */
export type NumericCode = typeof numericCodes[number];
`;
  return source.slice(1);
};
